//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietPhimBo
    {
        public int Id { get; set; }
        public int SoTap { get; set; }
        public string TenTapPhim { get; set; }
        public Nullable<System.DateTime> NgayPhatHanh { get; set; }
        public string DuongDanPhim { get; set; }
        public Nullable<int> LuotXem { get; set; }
    
        public virtual DanhSachPhim DanhSachPhim { get; set; }
    }
}
