//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MovieOnline.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhSachPhim
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DanhSachPhim()
        {
            this.ChiTietPhimBoes = new HashSet<ChiTietPhimBo>();
        }
    
        public int Id { get; set; }
        public string TenPhim { get; set; }
        public string HinhAnh { get; set; }
        public Nullable<System.DateTime> NgayThem { get; set; }
        public Nullable<System.DateTime> NgayPhatHanh { get; set; }
        public string TomTatNoiDung { get; set; }
        public string DuongDanPhim { get; set; }
        public Nullable<int> LuotXem { get; set; }
        public Nullable<double> DanhGia { get; set; }
        public Nullable<int> TheLoai { get; set; }
        public Nullable<int> LoaiPhim { get; set; }
        public Nullable<bool> HienThi { get; set; }
        public string Tag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChiTietPhimBo> ChiTietPhimBoes { get; set; }
        public virtual LoaiPhim LoaiPhim1 { get; set; }
        public virtual TheLoai TheLoai1 { get; set; }
    }
}
